version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2017

configuration: Release

platform:
- x86

cache:
- src/packages -> **/packages.config

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  before_build:
    - git submodule update --init --recursive
    - nuget restore cs/engine.sln
    - cmd: set DEVENV="%VS141COMNTOOLS%\..\IDE\devenv.exe" && %DEVENV% "cs/engine.sln" /upgrade
  build:
    parallel: true
    project: cs/engine.sln
    verbosity: minimal
  after_build:
    - xr_pack_build.cmd
  artifacts:
    - path: res/OpenXRay.*.7z
      name: OpenXRay.*.7z
    - path: res/Symbols.*.7z
      name: Symbols.*.7z

test: off
